# Generated by Django 3.1.2 on 2020-10-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201027_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='common_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
