# Generated by Django 3.1.2 on 2020-10-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20201027_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='common_name',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
