# Generated by Django 3.1.2 on 2020-11-04 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20201027_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.node'),
        ),
    ]
